### ISSUE TITLE
v2.0 - scrollbars do not appear unless height is provided

### ISSUE THREAD

**Issue by ddenev** [KingSora/OverlayScrollbars#481]
**Describe the bug**
After upgrading to 2.0 my scrollbars stopped working.

The only things I changed after the upgrade is:
- switched to the new styles import statement
- switched to the new named OverlayScrollbars import statement

And now all scrollbars that were previously working (with v1) are now not shown.
There is no error in the console and I see that all classes are properly attached to the host element.

The only way to make the scrollbars show is to explicitly give a fixed height to the host element. This was NOT previously necessary with v1. Why is that not documented as a breaking change and is that the way to go?

**Comment by KingSora** [comment]
Good day @ddenev 
Its not documented because I can't know every usecase and thus can't predict every behavior...

The described behavior seems odd though, `v2` also works without a fixed height it also works with other strategies (e.g. with max-height). 

Is it possible for you to create a minimal example on jsfiddle, codesandbox, stackblitz or as a standalone repo? I'll take a look asap then

**Comment by ddenev** [comment]
Here are 2 sandboxes that show my use-case:

A) https://codesandbox.io/s/overlayscrollbars-v2-height-required-issue-ci5gxz?file=/src/App.vue - this is with v2
B) https://codesandbox.io/s/overlayscrollbars-v1-height-required-issue-u0qbcx?file=/src/App.vue - this is with v1

A and B are absolutely identical, save the CSS and the `OverlayScrollbars` import statements.

The v1 works OK.
The v2 doesn't work. In order to make it work, you need to uncomment the CSS for the `.scroll-wrapper` class.

PS: Oh, and BTW, you have a typo in the v2 docs re importing the CSS for v1 (the Getting Started section) - you mention `'overlayscrollbars/styles/overlayscrollbars.css'` while the correct one is `'overlayscrollbars/css/OverlayScrollbars.css'`

**Comment by ddenev** [comment]
Something else - the `min-height` style on the top `div` is applied by my framework (Quasar) and is not under my control - I don't set any heights anywhere.

**Comment by KingSora** [comment]
@ddenev I see whats going on here..

`v1` always had struggle with `flexbox` and `grid`. Thus the consumer had to add all sorts of workarounds like the `os-host-flexbox` class [(link to the `v1` docs)](https://kingsora.github.io/OverlayScrollbars/v1/#!documentation/flexbox). In `v2` this is fixed and not needed anymore. 

You are using flexbox and in the `v1` example without the `os-host-flexbox` class. If you apply the class, the result is similar to what you get in the `v2` example. In short: the way your `v1` example works is wrong and the `v2` example is correct. 

You're might asking yourself how you can confirm whats correct and incorrect behavior. - Always rely on the native behavior. In your case simply add `overflow: scroll` or `overflow: auto` to the `scroll-wrapper` element and check whether scrollbars appear / scrolling is possible. (https://codesandbox.io/s/overlayscrollbars-v1-height-required-issue-forked-ncnrhg?file=/src/App.vue)

As you can see even natively no scrollbars are appearing with your markup. OverlayScrollbars will always follow the native behavior as closely as possible.

Regarding the "typo": I mentioned for old __node__ version you have to change the import path, not for the `v1` version of the plugin. This is due to the `exports` field in the `package.json` which is only supported in newer node versions.

**Comment by ddenev** [comment]
Thank you, @KingSora. I still have 2 questions:

1. In your example (https://codesandbox.io/s/overlayscrollbars-v1-height-required-issue-forked-ncnrhg?file=/src/App.vue) I can still see a scrollbar:
![image](https://user-images.githubusercontent.com/1393766/204527500-589d64aa-edda-4808-8f60-ea471befc920.png)
or is this not the scrollbar that I need?
2. Can you please guide me what do I need to do then in my case in order to make it work?

Thank you!

**Comment by KingSora** [comment]
@ddenev thats the scrollbar for the entire document.. you can disable this with:
```css
html, body {
  overflow: hidden
}
```

The answer to your 2nd question depends when you want the scrollbars to appear... whats the desired behavior? Since in the `v1` example the behavior was due to a bug I would like to have this defined

**Comment by KingSora** [comment]
@ddenev Cool, glad I could help! :) 

Do you think you still need guidance or can I consider this issue as resolved?

**Comment by ddenev** [comment]
Please consider this topic resolved. Thank you for your excellent assistance!
