### ISSUE TITLE
Keyboard control (arrows, PgUp/PgDown) not working until the scrolled area is clicked

### ISSUE THREAD

**Issue by borekl** [KingSora/OverlayScrollbars#76]
This is especially annoying when using OverlayScrollbar on BODY element. You cannot scroll it with keyboard until you click the page. Scrolling with mousewheel works however.

**Comment by KingSora** [comment]
Good day!

After some investigation I've found out that the default [activeElement](https://developer.mozilla.org/en-US/docs/Web/API/DocumentOrShadowRoot/activeElement) (the element which has the focus) is the body element. I don't know whether it can simply be fixed by changing the focus after you've initialized the plugin to the body element, but I'll try it. The fix would be to set the focus to the `os-viewport` element as this element is responsible for the scrolling.

Thanks for the issue though!

**Comment by hamed-ehtesham** [comment]
Hi Rene,
i have a suggestion too: delegate `body` events to `os-viewport`

and also thanks for the new version. it fixed a bug that i don't know what it was but caused a problem in last version for me i was about to first find out the problem and then let you know to fix it but you fixed it by new version. thanks

**Comment by KingSora** [comment]
@hamed-ehtesham Unfortunately it isn't that simple toe delegate events from one element to other elements... I've thought of that too in the past.
I know which bug you mean, I've figured out the cause after a very long investigation.

**Comment by hamed-ehtesham** [comment]
hi i spent some time trying to delegate event and you where right it's blocked by browser for security reasons to simulate user events except some exceptions like `click()` and `focus()`.
my best shot resulted [this](https://codepen.io/H4M3D3/pen/mQNbVR) but your solution works; i've tested it, the only thing you should consider is that `<div>`s are not focusable. the following code works

```js
const instance = OverlayScrollbars(document.body, {});
let elements = instance.getElements();

// make viewport focusable
elements.viewport.tabIndex = -1;
elements.viewport.focus();
```

the bug was about some inaccurate enormous width and height, and thanks again for fixing it. and i'm glad my demo helped you find it although that demo wasn't where i encountered it myself

**Comment by KingSora** [comment]
@hamed-ehtesham my solution is actually very similar to yours, but I've included some checks and a cleanup to handle everything as correctly as possible:

```javascript
//set the focus on the viewport element so you dont have to click on the page to use keyboard keys (up / down / space) for scrolling
if(document.activeElement == targetElement && _viewportElement[0].focus) {
	//set a tabindex to make the viewportElement focusable
	_viewportElement.attr('tabindex', '-1');
	_viewportElement[0].focus();
	/* the tabindex has to be removed due to;
	 * If you set the tabindex attribute on an <div>, then its child content cannot be scrolled with the arrow keys unless you set tabindex on the content, too
	 * https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex
	 */
	_viewportElement.one(_strMouseTouchDownEvent, function() { 
		_viewportElement.removeAttr('tabindex'); 
	});
}
```
Thank you very much for your help!

**Comment by hamed-ehtesham** [comment]
you're welcome buddy, Anytime.

**Comment by KingSora** [comment]
I've implemented this in [v1.6.1](https://github.com/KingSora/OverlayScrollbars/releases/tag/v1.6.1).
I hope it works as you expect it to work!

**Comment by borekl** [comment]
@KingSora Looks good to me, thanks for the fix.

**Comment by KingSora** [comment]
@borekl Glad I could help!

**Comment by agusterodin** [comment]
I am still having this issue. Is there some sort of option I have to enable to auto focus? I am using the scrollbars on the body element

**Comment by KingSora** [comment]
@agusterodin thats weird... which browser and OverlayScrollbars version are you using?

**Comment by agusterodin** [comment]
It is worth mentioning that this is a react app and I am not wrapping body directly but wrapping the contents of my app in a div directly inside the react application mounting point (<div id="app">). I am on the latest version of Chrome on MacOS (80.0.3987.106)

here is my app's basic dom structure 

<img width="576" alt="Screen Shot 2020-02-16 at 2 24 36 PM" src="https://user-images.githubusercontent.com/10248395/74611270-2ef96900-50c8-11ea-81d9-f57a7eeb6fe5.png">
 
Overlay Scrollbars version 1.10.3 and the 0.2.1 version of the React wrapper

I currently do this (see below) to reset scroll to top of page on every router transition. I was thinking of setting focus on the overlay scrollbars dom element on every router transition there well but am afraid this isn't best practice, especially if your library already handles this.

<img width="846" alt="Screen Shot 2020-02-16 at 2 26 40 PM" src="https://user-images.githubusercontent.com/10248395/74611335-c1017180-50c8-11ea-8144-e6175973428c.png">

**Comment by KingSora** [comment]
@agusterodin this explains it... OverlayScrollbars only does it if the target element is the `body` element. In your case it's just a `div` which has the whole size of the viewport. In this case you could do it in the way you explained (my library doesn't do it much differently if its the body element). You have to be careful to [apply](https://github.com/KingSora/OverlayScrollbars/blob/master/js/OverlayScrollbars.js#L6445) `tabindex="-1"`, else the browser won't apply the focus.

You could also just apply OverlayScrollbars to the body element, your styling has to change in this case I think..

**Comment by agusterodin** [comment]
How would I apply it to the body element in React? To my knowledge, a component can not be mounted anywhere above react's mounting point (the element with the id "app" in my case). Are you saying to just use the vanilla version of the library inside of my react app and set it to attach to document.body on router component's initial mount? I feel like react wouldn't play nicely with this (but I could just be paranoid). 

It really would be nice to get these scrollbars directly attached to body because putting my site content in a scrollable div causes the unintended behavior on mobile version of chrome of the address bar not "tucking away" once you start scrolling through the site content.

I wonder if React portals are the key to solving this issue, probably not though.

**Comment by agusterodin** [comment]
Initializing overlay scrollbars directly with: 
```
document.addEventListener('DOMContentLoaded', function () {
    OverlayScrollbars(document.querySelectorAll('body'), {})
})
```

This works well and doesn't interfere with React operation whatsoever. The lesson learned is that this library's React wrapper works for any scenario other than mounting scrollbars directly to body.

Focus on initial page load works well but doesn't reset when page changes (since this is a SPA) and doesn't automatically return back when I click on certain things on the page, particularly absolutely positioned elements like my navbar. 

My only other slight issue is that the address bar "tuck away" never happens in mobile Chrome but that issues is completely unrelated to React. I think this is impossible to get around with the way this library needs to structure the DOM in order to operate.

**Comment by KingSora** [comment]
@agusterodin Yes, the address bar issue was mentioned before. Unfortunately there isn't a possibility to solve it right now.. But I've posted here how it can be solved in the future: https://github.com/KingSora/OverlayScrollbars/issues/61#issuecomment-519809455

**Comment by iamarpitpatidar** [comment]
@KingSora I am using the latest version. But I am still having the same issue just same arrow keys doesn't work but mouse scroll works, I have also tried your solution but it doesn't works in my case.
